package com.ctw.spark

object Central {
  
    def main(args: Array[String]) {
      
      //ClaimsLR     //uncomment for Linear Regression
      //ClaimGBT        //uncomment for Gradient Boosting Trees
      //ClaimsRF        //uncomment for Gradient Boosting Trees
      ClaimsRFReuse  // get the model file generated by ClaimsRF (saved on model/RF_model/) and use it to make new predictions 
      
      
   }
}